repos:
  # Warning-only Python linting (won't block commits)
  - repo: local
    hooks:
      - id: flake8-warn
        name: Flake8
        entry: bash -c 'cd backend && flake8 --extend-ignore=E203,W503 --max-line-length=99 --exclude=.venv . || false'
        language: system
        files: .*\.py$
        pass_filenames: false

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: bash -c 'cd backend && isort . --skip=.venv || false'
        language: system
        files: .*\.py$
        pass_filenames: false

  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c 'cd backend && black . --exclude=.venv || false'
        language: system
        files: .*\.py$

  # Basic file checks (these can still block for critical issues)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
      - id: check-yaml  # Validates YAML syntax
        args: ['--allow-multiple-documents']
        exclude: ^helm/.*\.yaml$|^tests/integration/.*\.tavern\.yaml$  # Exclude Helm templates and Tavern test files
      - id: check-json  # Validates JSON syntax
        exclude: ^frontend/.*$  # Exclude frontend - handled by ESLint
      - id: trailing-whitespace
        exclude: .*\.svg$  # Exclude all SVG files
      - id: end-of-file-fixer
        exclude: .*\.svg$|.*\.csv$|.*\.txt$  # Exclude SVG, CSV, and TXT files

  # Warning-only Helm linting (won't block commits)
  - repo: local
    hooks:
      - id: helm-lint-warn
        name: Helm Lint
        entry: bash -c 'cd helm/product-recommender-system/ && helm lint . && cd ../minio/ && helm lint . && cd ../pipeline-server/ && helm lint . || false'
        language: system

  # Warning-only Python linting (won't block commits)
  - repo: local
    hooks:
      - id: prettier-warn
        name: prettier
        entry: bash -c 'cd frontend && npx prettier --check . || false'
        language: system
