---
{{- $jobName := "kfp-run-job" }}
{{- $existingJob := (lookup "batch/v1" "Job" .Release.Namespace $jobName) }}
{{- if not $existingJob }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName }}
  labels:
    pipelines.kubeflow.org/v2_component: 'true'
spec:
  template:
    {{- include "product-recommender-system.pipeline-job-template" . | nindent 4 }}
{{- end }}

---
{{- $cronJobName := "kfp-run-cronjob" }}
{{- $existingCronJob := (lookup "batch/v1" "CronJob" .Release.Namespace $cronJobName) }}
{{- if not $existingCronJob }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $cronJobName }}
  labels:
    pipelines.kubeflow.org/v2_component: 'true'
spec:
  schedule: "0 0 * * *"  # Run daily at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        {{- include "product-recommender-system.pipeline-job-template" . | nindent 8 }}
{{- end }}
