name: Build and push backend/frontend image

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - 'frontend/**'
  workflow_run:
    workflows: ["Build and push recommendation-core image"]
    types:
      - completed
    branches:
    - main
  workflow_dispatch:

env:
  BACKEND_DIR: backend

jobs:
  build-backend-image:
    name: Build and Push Backend/Frontend Image
    runs-on: ubuntu-latest
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    strategy:
      matrix:
        include:
          - name: product-recommender-frontend-backend
            context: .
            image-name: product-recommender-frontend-backend
    defaults:
      run:
        working-directory: ${{ env.BACKEND_DIR }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Set version from run number
        id: version
        run: |
          echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Containerfile
          push: true
          tags: |
            quay.io/rh-ai-kickstart/${{ matrix.image-name }}:${{ steps.version.outputs.tag }}
            quay.io/rh-ai-kickstart/${{ matrix.image-name }}:latest
          build-args: |
            IMAGE_TAG=${{ steps.version.outputs.tag }}
